// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupInfo = { exists: boolean, 
/**
 * Backup file's last-modified time, ms since the Unix epoch.
 */
modifiedMs: number | null, };
