// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KickConfig } from "./KickConfig";

/**
 * External tagging — `"Twitch"` or `{"Kick": {...}}`.
 * Matches NOALBS v2 `config::ConfigChatPlatform` (no `#[serde(tag)]`).
 */
export type ChatPlatform = "Twitch" | { "Kick": KickConfig };
