// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatPlatform } from "./ChatPlatform";
import type { CommandInfo } from "./CommandInfo";

/**
 * Matches NOALBS v2 `config::Chat` with `#[serde(rename_all = "camelCase", default)]`.
 */
export type Chat = { platform: ChatPlatform, username: string, admins: Array<string>, ignoreUsers: Array<string>, language: string, prefix: string, enablePublicCommands: boolean, enableModCommands: boolean, enableAutoStopStreamOnHostOrRaid: boolean, announceRaidOnAutoStop: boolean, commands: { [key in string]?: CommandInfo } | null, };
