// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandInfo = { permission: string | null, userPermissions: Array<string> | null, alias: Array<string> | null, };
