// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionalOptions } from "./OptionalOptions";
import type { OptionalScenes } from "./OptionalScenes";
import type { SoftwareConnection } from "./SoftwareConnection";
import type { Switcher } from "./Switcher";
import type { User } from "./User";

export type Config = { user: User, switcher: Switcher, software: SoftwareConnection, chat: any, optionalScenes: OptionalScenes, optionalOptions: OptionalOptions, };
