// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoalbsStatus } from "./NoalbsStatus";

export type DashboardSnapshot = { running: boolean, uptimeSecs: bigint | null, version: string | null, status: NoalbsStatus, };
