// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchingScenes } from "./SwitchingScenes";

export type DependsOn = { name: string, backupScenes: SwitchingScenes, };
