// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The .env values the GUI manages. Other lines in the file are preserved.
 */
export type EnvValues = { twitchBotUsername: string | null, twitchBotOauth: string | null, apiPort: string | null, logDir: string | null, };
