// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IrlhostingConfig = { statsUrl: string, application: string | null, key: string | null, publisher: string | null, };
