// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStream } from "./LogStream";

export type LogLine = { seq: bigint, stream: LogStream, text: string, };
