// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsConnection } from "./ObsConnection";
import type { TwitchStatus } from "./TwitchStatus";

export type NoalbsStatus = { obs: ObsConnection, currentScene: string | null, lastSwitchType: string | null, switcherState: string | null, user: string | null, twitch: TwitchStatus, };
