// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerAuth } from "./ServerAuth";

export type NodeMediaServerConfig = { statsUrl: string, application: string, key: string, auth: ServerAuth | null, };
