// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionPair } from "./CollectionPair";

export type ObsConfig = { host: string, password: string | null, port: number, collections: { [key in string]?: CollectionPair } | null, };
