// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptionalOptions = { twitchTranscodingCheck: boolean, twitchTranscodingRetries: bigint, twitchTranscodingDelaySeconds: bigint, offlineTimeout: number | null, recordWhileStreaming: boolean, switchToStartingSceneOnStreamStart: boolean, switchFromStartingSceneToLiveScene: boolean, };
