// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auth used by NodeMediaServer and Mediamtx.
 * No rename_all — fields serialise as "username" / "password" (already lowercase).
 */
export type ServerAuth = { username: string, password: string, };
