// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinarySource } from "./BinarySource";
import type { Theme } from "./Theme";

export type Settings = { binarySource: BinarySource, binaryPath: string | null, installedVersion: string | null, workingDir: string | null, checkUpdatesOnStartup: boolean, theme: Theme, autoStart: boolean, };
