// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SrtLiveServerConfig = { statsUrl: string, publisher: string, apiKey: string | null, };
