// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BelaboxConfig } from "./BelaboxConfig";
import type { IrlhostingConfig } from "./IrlhostingConfig";
import type { MediamtxConfig } from "./MediamtxConfig";
import type { NginxConfig } from "./NginxConfig";
import type { NimbleConfig } from "./NimbleConfig";
import type { NodeMediaServerConfig } from "./NodeMediaServerConfig";
import type { OpenIrlConfig } from "./OpenIrlConfig";
import type { RistConfig } from "./RistConfig";
import type { SrtLiveServerConfig } from "./SrtLiveServerConfig";
import type { XiuConfig } from "./XiuConfig";

/**
 * Each variant wraps a config struct so that `rename_all = "camelCase"` can be
 * applied per-struct rather than to the enum (which would also rename variant names).
 * The tag `"type"` uses the variant name as-is (PascalCase) matching NOALBS v2.
 */
export type StreamServerKind = { "type": "Nginx" } & NginxConfig | { "type": "NodeMediaServer" } & NodeMediaServerConfig | { "type": "Nimble" } & NimbleConfig | { "type": "SrtLiveServer" } & SrtLiveServerConfig | { "type": "Belabox" } & BelaboxConfig | { "type": "Mediamtx" } & MediamtxConfig | { "type": "Rist" } & RistConfig | { "type": "Xiu" } & XiuConfig | { "type": "OpenIRL" } & OpenIrlConfig | { "type": "Irlhosting" } & IrlhostingConfig;
