// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependsOn } from "./DependsOn";
import type { StreamServerKind } from "./StreamServerKind";
import type { SwitchingScenes } from "./SwitchingScenes";

export type StreamServerEntry = { streamServer: StreamServerKind, name: string, priority: number | null, overrideScenes: SwitchingScenes | null, dependsOn: DependsOn | null, enabled: boolean, };
