// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchingScenes } from "./SwitchingScenes";
import type { Triggers } from "./Triggers";

export type Switcher = { bitrateSwitcherEnabled: boolean, onlySwitchWhenStreaming: boolean, instantlySwitchOnRecover: boolean, autoSwitchNotification: boolean, retryAttempts: number, triggers: Triggers, switchingScenes: SwitchingScenes, streamServers: any[], };
